### ISSUE TITLE
Unable to install The 3rd party library

### ISSUE THREAD

**Issue by Shotaro-N** [paulald/loomo-algodev-mirror-paul-elevator#1]
Unable to install The 3rd party library.

http://pan.aprwork.com/index.php/s/68hUtg6ZfC9bAvj

Is this URL valid?
Or is it the same as loomo-algodev?

**Comment by paulald** [comment]
Hello this repository is no longer being worked on or updated. The URL is no longer valid, you should visit https://github.com/segway-robotics/loomo-algodev for installation of 3rd party libraries as it is based on an older version loomo-algodev. It should work with the third party librairies listed there.

**Comment by Shotaro-N** [comment]
Thank you very much. Paulald.
I'm sorry, but I have one more question to ask.

I selected Tensorflow App with a macro and made it work.
But it crashes.

If you ask a developer of an older version of loomo-algodev, there is no reply, so if you have any questions, please let me know.

I'm sorry.

**Comment by paulald** [comment]
I think it is maybe because you didn't save the model on Loomo? Which has to be done with the 'adb push' command. I mention the command briefly in 2.2.1 of the tutorial at the end of my report in this folder: https://github.com/paulald/loomo-algodev-mirror-paul-elevator/tree/master/algo_app/src/main/jni/app_elevator (the links may no longer be valid as they are old)
On my version I'm sure it worked...

I cannot test your code as I no longer have a Loomo at my disposal.

**Comment by Shotaro-N** [comment]
I thank you for your kind explanation.

Very helpful! !! !!
Thank you very much.
